version: '3'

networks:
  mercado-network:

services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=''
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    networks:
      - mercado-network